name: Deploy Stock API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install
          cd backend && npm install && cd ..
          cd frontend && npm install && cd ..
          cd infrastructure && npm install && cd ..
      
      - name: Build backend
        run: cd backend && npm run build && cd ..
      
      - name: Build frontend
        run: cd frontend && npm run build && cd ..
      
      - name: Deploy infrastructure
        run: cd infrastructure && npm run cdk:deploy -- --require-approval never
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
